from .data_loaders import load_txt, load_url, load_file
from .data_cleaners import (
    clean_with_regex,
    clean_html,
    clean_markdown,
    markdown_to_text,
)


DATA_LOADERS = {
    ".docx": load_file,
    ".html": load_txt,
    ".md": load_txt,
    ".pdf": load_file,
    ".txt": load_txt,
    ".json": load_file,
    ".jpeg": load_file,
    ".jpg": load_file,
    ".mp3": load_file,
    ".m4a": load_file,
    ".png": load_file,
    ".ppt": load_file,
    ".pptx": load_file,
    ".rar": load_file,
    ".tar": load_file,
    ".wav": load_file,
    ".xls": load_file,
    ".xlsx": load_file,
    ".xml": load_file,
    ".zip": load_file,
    ".7z": load_file,
    ".aac": load_file,
    ".csv": load_file,
    ".doc": load_file,
    ".gz": load_file,
    ".htm": load_file,
    "url": load_url,
}

DATA_CLEANERS = {
    ".docx": markdown_to_text,
    ".html": clean_html,
    ".md": clean_markdown,
    ".pdf": markdown_to_text,
    ".txt": clean_with_regex,
    ".json": markdown_to_text,
    ".jpeg": markdown_to_text,
    ".jpg": markdown_to_text,
    ".mp3": markdown_to_text,
    ".m4a": markdown_to_text,
    ".png": markdown_to_text,
    ".ppt": markdown_to_text,
    ".pptx": markdown_to_text,
    ".rar": markdown_to_text,
    ".tar": markdown_to_text,
    ".wav": markdown_to_text,
    ".xls": markdown_to_text,
    ".xlsx": markdown_to_text,
    ".xml": markdown_to_text,
    ".zip": markdown_to_text,
    ".7z": markdown_to_text,
    ".aac": markdown_to_text,
    ".csv": markdown_to_text,
    ".doc": markdown_to_text,
    ".gz": markdown_to_text,
    ".htm": markdown_to_text,
}
